version: '3.8'
services:     
  database:
    image: "postgres"
    container_name: barber-book-db
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=123456"
      - "POSTGRES_DB=barber_book"
      - "TZ=America/Sao_Paulo"
    ports:
      - "5437:5432"
    volumes:
      - ./sql/barberBook.sql:/docker-entrypoint-initdb.d/barberBook.sql
    restart: always
  backend:
    build:
       context: .
       dockerfile: ./Dockerfile
    container_name: barber-book-backend
    depends_on:
      - database
    ports:
       - "5000:5000"
    restart: always
volumes:
  pg-data: {}