// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/barber/client/create": {
            "post": {
                "description": "Cria um novo cliente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "Create client",
                "parameters": [
                    {
                        "description": "Create client",
                        "name": "client",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.CreateClient"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sem conteúdo"
                    }
                }
            }
        },
        "/barber/client/list": {
            "get": {
                "description": "Lista todos os clientes da barbearia",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "List os clientes da barbearia",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/client.ListClients"
                            }
                        }
                    }
                }
            }
        },
        "/barber/create": {
            "post": {
                "description": "Cria um novo barbeiro",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "barber"
                ],
                "summary": "Criação dos barbeiros",
                "parameters": [
                    {
                        "description": "Create barber",
                        "name": "barber",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/barber.CreateBarber"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sem conteúdo"
                    }
                }
            }
        },
        "/barber/list": {
            "get": {
                "description": "Lista todos os barbeiros da barbearia",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "barber"
                ],
                "summary": "List os barbeiros da barbearia",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/barber.ListBarbers"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "barber.CreateBarber": {
            "type": "object",
            "required": [
                "contato",
                "nome"
            ],
            "properties": {
                "contato": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "barber.ListBarbers": {
            "type": "object",
            "properties": {
                "contato": {
                    "type": "string"
                },
                "data_atualizacao": {
                    "type": "string"
                },
                "data_criacao": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "client.CreateClient": {
            "type": "object",
            "required": [
                "contato",
                "email",
                "nome",
                "senha"
            ],
            "properties": {
                "contato": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "senha": {
                    "type": "string"
                }
            }
        },
        "client.ListClients": {
            "type": "object",
            "properties": {
                "contato": {
                    "type": "string"
                },
                "data_atualizacao": {
                    "type": "string"
                },
                "data_criacao": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "senha": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Barber Shop API",
	Description:      "This is a sample server Petstore server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	//LeftDelim:        "{{",
	//RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
