basePath: /
definitions:
  barber.CreateBarber:
    properties:
      contato:
        type: string
      nome:
        type: string
    required:
    - contato
    - nome
    type: object
  barber.ListBarbers:
    properties:
      contato:
        type: string
      data_atualizacao:
        type: string
      data_criacao:
        type: string
      id:
        type: integer
      nome:
        type: string
    type: object
  client.CreateClient:
    properties:
      contato:
        type: string
      email:
        type: string
      nome:
        type: string
      senha:
        type: string
    required:
    - contato
    - email
    - nome
    - senha
    type: object
  client.ListClients:
    properties:
      contato:
        type: string
      data_atualizacao:
        type: string
      data_criacao:
        type: string
      email:
        type: string
      id:
        type: integer
      nome:
        type: string
      senha:
        type: string
    type: object
host: localhost:5000
info:
  contact: {}
  description: This is a sample server Petstore server.
  title: Barber Shop API
  version: "1.0"
paths:
  /barber/client/create:
    post:
      consumes:
      - application/json
      description: Cria um novo cliente
      parameters:
      - description: Create client
        in: body
        name: client
        required: true
        schema:
          $ref: '#/definitions/client.CreateClient'
      produces:
      - application/json
      responses:
        "200":
          description: Sem conteúdo
      summary: Create client
      tags:
      - client
  /barber/client/list:
    get:
      consumes:
      - application/json
      description: Lista todos os clientes da barbearia
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/client.ListClients'
            type: array
      summary: List os clientes da barbearia
      tags:
      - client
  /barber/create:
    post:
      consumes:
      - application/json
      description: Cria um novo barbeiro
      parameters:
      - description: Create barber
        in: body
        name: barber
        required: true
        schema:
          $ref: '#/definitions/barber.CreateBarber'
      produces:
      - application/json
      responses:
        "200":
          description: Sem conteúdo
      summary: Criação dos barbeiros
      tags:
      - barber
  /barber/list:
    get:
      consumes:
      - application/json
      description: Lista todos os barbeiros da barbearia
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/barber.ListBarbers'
            type: array
      summary: List os barbeiros da barbearia
      tags:
      - barber
swagger: "2.0"
